# Generated by Django 4.2.7 on 2024-10-14 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelservicio',
            name='id_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning_travel.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelservicio',
            name='id_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning_travel.servicio'),
        ),
    ]
