# Generated by Django 4.2.7 on 2024-06-11 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='fecha_agregado',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
