# Generated by Django 4.2.7 on 2024-05-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='dueño',
            new_name='propietario',
        ),
    ]
