# Generated by Django 4.2.7 on 2024-10-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comodidad',
            name='descripcion',
        ),
    ]
