# Generated by Django 4.2.7 on 2024-09-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0002_mensaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='id_hotel',
            new_name='id_destinatario',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='id_usuario',
            new_name='id_remitente',
        ),
    ]
