# Generated by Django 4.2.7 on 2024-05-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0002_rename_dueño_hotel_propietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservausuario',
            name='estado_reserva',
            field=models.IntegerField(choices=[(1, 'reservada'), (2, 'libre'), (3, 'cancelada')], default=1),
        ),
    ]
