# Generated by Django 4.2.7 on 2024-05-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0002_rename_dueño_hotel_propietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='cantidad_habitaciones',
        ),
    ]
