# Generated by Django 4.2.7 on 2024-10-14 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0002_alter_hotelservicio_id_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='id_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning_travel.hotel'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
