# Generated by Django 4.2.7 on 2024-09-06 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0003_rename_id_hotel_mensaje_id_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='id_destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='id_remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL),
        ),
    ]
