# Generated by Django 4.2.7 on 2024-05-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0003_alter_reservausuario_estado_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservausuario',
            name='fecha_realizacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
