# Generated by Django 4.2.7 on 2024-10-14 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0004_alter_foto_id_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservausuario',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning_travel.reserva'),
        ),
        migrations.AlterField(
            model_name='reservausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
