# Generated by Django 4.2.7 on 2024-09-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0005_mensaje_fecha_envio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='fecha_envio',
            new_name='fecha',
        ),
    ]
