# Generated by Django 4.2.7 on 2024-10-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0006_alter_reserva_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservausuario',
            name='estado_reserva',
            field=models.IntegerField(choices=[(1, 'reservada'), (2, 'En curso'), (3, 'cancelada'), (4, 'finalizado')], default=1),
        ),
    ]
