# Generated by Django 4.2.7 on 2024-10-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0007_alter_reservausuario_estado_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Anfitrion'), (3, 'Cliente')], default=3),
        ),
    ]
