# Generated by Django 4.2.7 on 2024-02-09 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0007_rename_reportes_reporte_and_more'),
        ('planning_travel', '0008_alter_usuario_foto'),
    ]

    operations = [
    ]
