# Generated by Django 4.2.7 on 2024-03-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0009_merge_20240209_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='ciudad',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='dueño',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(upload_to='planning_travel/media/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(upload_to='planning_travel/media/'),
        ),
    ]
