# Generated by Django 4.2.7 on 2024-03-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0010_hotel_ciudad_hotel_dueño_alter_cliente_foto_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='precio',
        ),
        migrations.AddField(
            model_name='hotel',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=250),
            preserve_default=False,
        ),
    ]
