# Generated by Django 4.2.7 on 2024-03-27 21:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0011_remove_habitacion_foto_remove_habitacion_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=300)),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='La puntuación debe ser como mínimo 1.'), django.core.validators.MaxValueValidator(5, message='La puntuación debe ser como máximo 5.')])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.hotel')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='id_comentario',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Puntuacion',
        ),
    ]
