# Generated by Django 4.2.7 on 2024-03-28 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0012_opinion_remove_puntuacion_id_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('icono', models.FileField(upload_to='planning_travel/svg_services/')),
            ],
        ),
        migrations.CreateModel(
            name='HotelServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.hotel')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.servico')),
            ],
        ),
    ]
