# Generated by Django 4.2.7 on 2024-03-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0013_servico_hotelservicio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servico',
            new_name='Servicio',
        ),
    ]
