# Generated by Django 4.2.7 on 2024-04-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0014_rename_servico_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.usuario'),
        ),
    ]
