# Generated by Django 4.2.7 on 2024-04-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0015_alter_hotel_dueño'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comodidad',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='hotelcomodidad',
            name='dispone',
        ),
        migrations.AddField(
            model_name='hotelcomodidad',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
